version: '3'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: laravel-docker
        working_dir: /srv/app
        ports:
            - 8080:80
        volumes:
            - .:/srv/app
        links:
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: restaurant_manager
            DB_USERNAME: app
            DB_PASSWORD: password
    mysql:
        image: mysql:5.7
        ports:
            - 13306:3306
        environment:
            MYSQL_DATABASE: restaurant_manager
            MYSQL_USER: app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
    node:
        image: node
        working_dir: /srv/app
        volumes:
            - .:/srv/app
        command: npm install
            
        